### ISSUE TITLE
Asus rog kernel issue

### ISSUE THREAD

**Issue by Alex-Beh** [arglebargle-arch/xanmod-rog-PKGBUILD#1]
Just by any chance, I am using Ubuntu 20.04 on my Asus ROG G15 2021 with kernel version: 5.12.0-051200rc8-generic. However, everytime I press the keyboard, the following window pops up. May I know the purpose of this repo and how to use it? Thanks in advance.

The related file should be this one [0001-HID-asus-filter-G713-G733-key-event-to-prevent-shutd.patch](https://github.com/arglebargle-arch/xanmod-rog-PKGBUILD/blob/master/asus-linux-patches/0001-HID-asus-filter-G713-G733-key-event-to-prevent-shutd.patch). But how can I use it?
![image](https://user-images.githubusercontent.com/66585558/117148394-c2f84300-ade8-11eb-973e-10f5f06e84df.png)

**Comment by foundObjects** [comment]
This repo is just for tracking my personal Arch Linux kernel package source, there isn't much you can do with it yourself on Ubuntu.

The patch set I'm using is from https://asus-linux.org/ but they only provide support for Fedora and (unofficially) Arch. Your best bet if you need support is to install Fedora and join their discord, then they'll be able to help you get up to speed.
