### ISSUE TITLE
xanmond_5.12.4 compile error

### ISSUE THREAD

**Issue by cupkax** [arglebargle-arch/xanmod-rog-PKGBUILD#2]
There is an in issue during the compilation for kernel 5.12.4 caused by [0001-Add-jack-toggle-support-for-headphones-on-Asus-ROG-Z.patch](https://github.com/arglebargle-arch/xanmod-rog-PKGBUILD/blob/master/asus-linux-patches/0001-Add-jack-toggle-support-for-headphones-on-Asus-ROG-Z.patch)

The compilation does succeed if the patch is removed.

**Comment by foundObjects** [comment]
Fixed! That patch needed to be reworked for 5.12.4.

I rewrote all of the janky patch application code while I was at it too, now you can skip patches based on filename or bash glob patterns and the build will properly squeal at you when patches either break or are redundant after they've been upstreamed. Take a look at the patch application code, I'm pretty pleased by how well it came out.
