### ISSUE TITLE
AUR entry

### ISSUE THREAD

**Issue by SelfRef** [arglebargle-arch/xanmod-rog-PKGBUILD#3]
I don't see this kernel in AUR repository list. Is there any reason not to put it there for convenience?

**Comment by aviallon** [comment]
It is because AUR rejected the commit history. I had to rewrite most of it.

**Comment by aviallon** [comment]
Here it is, fixed: https://github.com/aviallon/xanmod-rog-PKGBUILD

**Comment by SelfRef** [comment]
Many thanks!

Direct links to packages for convenience:
[linux-xanmod-rog](https://aur.archlinux.org/packages/linux-xanmod-rog/)
[linux-xanmod-rog-headers](https://aur.archlinux.org/packages/linux-xanmod-rog-headers/)
